# Analyzing the Features of Passengers that were a Part of the Titanic Sinking Using Different Machine Learning Algorithms
##Jai Naidu
##11/28/16
##Period 8
##Ms. Anderson

# Part 1

In [2]:
##   1	 Class (0 = crew, 1 = first, 2 = second, 3 = third)
##  2 	 Age   (1 = adult, 0 = child)
##  3	 Sex   (1 = male, 0 = female)
##  4	 Survived (1 = yes, 0 = no)

In [13]:
#code to import a csv and convert it to a numpy array
#import the numpy library
import numpy as np
#open the file
raw_data = open("titanic.csv")
# load the CSV file as a numpy matrix
dataset = np.loadtxt(raw_data, delimiter=",")
#'shape' is the dimensions of the matrix
print(dataset.shape)
# separate the data from the target attributes
X = dataset[:,0:3]
y = dataset[:,3]
print(X)
print(y)

(2201, 4)
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 ..., 
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]]
[ 1.  1.  1. ...,  0.  0.  0.]


In [14]:
from sklearn import tree
import random
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=.5)

my_classifier=tree.DecisionTreeClassifier();
my_classifier=my_classifier.fit(X_train, y_train)
predictions=my_classifier.predict(X_test)

from sklearn.metrics import accuracy_score
print(accuracy_score(predictions, y_test))

#0.795640326975, 0.792915531335, 0.792007266122, 0.788374205268, 0.785649409628

0.77838328792


In [26]:
import random
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=.5)

from sklearn import neighbors
knn_classifier = neighbors.KNeighborsClassifier()
knn_classifier = knn_classifier.fit(X_train, y_train)
knn_predictions = knn_classifier.predict(X_test)

print(accuracy_score(knn_predictions, y_test))

#0.570390554042, 0.762034514078, 0.785649409628, 0.792007266122, 0.800181653043

0.782016348774


In [27]:
import random
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=.5)

from sklearn import ensemble
rf_classifier = ensemble.RandomForestClassifier()
rf_classifier = rf_classifier.fit(X_train, y_train)
rf_predictions = rf_classifier.predict(X_test)

print(accuracy_score(rf_predictions, y_test))

#0.777475022707, 0.782924613987, 0.780199818347, 0.786557674841, 0.779291553134

0.783832879201


In the end I decided to use the decision tree classifier to predict the outcomes of the situation in the next part. This classifier had the highest mean accuracy (I tested each classifier's accuracy 5 times).

# Part 2

In [25]:
import random
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=.5)

from sklearn import tree
tree_classifier = tree.DecisionTreeClassifier();
tree_classifier = tree_classifier.fit(X_train, y_train)
tree_predictions = tree_classifier.predict(X_test)

from sklearn.metrics import accuracy_score

clf = tree.DecisionTreeClassifier()
clf = clf.fit(X,y)

print("An adult male in the 3rd class is predicted to die:")
print(clf.predict([3,1,1]))
print("An adult female in the 1st class is predicted to live:")
print(clf.predict([1,1,0]))
print("A female child in the 1st class is predicted to live:")
print(clf.predict([1,0,0]))

An adult male in the 3rd class is predicted to die:
[ 0.]
An adult female in the 1st class is predicted to live:
[ 1.]
A female child in the 1st class is predicted to live:
[ 1.]


C:\Users\jai\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\jai\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\jai\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


# Part 3

In [22]:
print("Which quality is the most influential to the condition of any given person aboard the Titanic during the crash?")
print(clf.predict([1,1,1]))
print(clf.predict([3,0,1]))
print(clf.predict([3,1,0]))
print(clf.predict([2,1,1]))
print(clf.predict([0,1,1]))
print(clf.predict([2,1,0]))

Which quality is the most influential to the condition of any given person aboard the Titanic during the crash?
[ 0.]
[ 0.]
[ 0.]
[ 0.]
[ 0.]
[ 1.]


C:\Users\jai\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\jai\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\Users\jai\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
C:\U

In this part I decided to find out the most influential quality for an individual's survival through trial and error. I tested several different individuals and tested them to see if they would live or die. I altered 1 or 2 qualities at a time and eventually came to the conclusion that age is the deciding factor.

In [28]:
X = dataset[:,0:1]
y = dataset[:,3]

import random
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=.5)

from sklearn import tree
tree_classifier = tree.DecisionTreeClassifier();
tree_classifier = tree_classifier.fit(X_train, y_train)
tree_predictions = tree_classifier.predict(X_test)

print("Using class as the only feature, the accuracy of the classifier is:")
print(accuracy_score(predictions, y_test))
print("")
#
X = dataset[:,1:2]
y = dataset[:,3]

import random
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=.5)

from sklearn import tree
tree_classifier = tree.DecisionTreeClassifier();
tree_classifier = tree_classifier.fit(X_train, y_train)
tree_predictions = tree_classifier.predict(X_test)

print("Using age as the only feature, the accuracy of the classifier is:")
print(accuracy_score(predictions, y_test))
print("")
#
X = dataset[:,2:3]
y = dataset[:,3]

import random
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=.5)

from sklearn import tree
tree_classifier = tree.DecisionTreeClassifier();
tree_classifier = tree_classifier.fit(X_train, y_train)
tree_predictions = tree_classifier.predict(X_test)

print("Using gender as the only feature, the accuracy of the classifier is:")
print(accuracy_score(predictions, y_test))
print("")

Using class as the only feature, the accuracy of the classifier is:
0.63578564941

Using age as the only feature, the accuracy of the classifier is:
0.636693914623

Using gender as the only feature, the accuracy of the classifier is:
0.615803814714



In [ ]:
#0.647593097184  0.627611262489  0.6148955495    0.632152588556  0.628519527702

#0.654859218892  0.639418710263  0.653950953678  0.650317892825  0.643051771117

#0.644868301544  0.645776566757  0.643960036331  0.637602179837  0.628519527702

After finding the average of the accuracy per feature in the dataset I determined that age is the determining factor for surivival during the Titanic crash.

# Conclusion

After testing 3 different classifiers on this data set, I determined that the decision tree classifier was the most accurate. In comparison, the Kneighbors classifier was all over the place as far as accuracy goes; the random forest classifier, however, came in a close second.
After training the data set (using the decision tree classifier) the prediction were around 79 percent accurate.
Lastly, I found the most influential factor in survival during the titanic crash was age. I am not too surprised by this result. I hypothesized that the most determining factor of survival would be age or gender. My assumption would be that they evacuated the women and children first, prioritizing the children. I think that in all of the chaos class may have been the least of anyone’s worries. Aside from the crew (I would assume most crew was aiding in the evacuation) differentiating people by class would be near impossible when everyone is clustered together trying to get off the boat.